### ISSUE TITLE
Poor results on non-training sets with Pretrained Models

### ISSUE THREAD

**Issue by primejava** [lyndonzheng/Pluralistic-Inpainting#25]
![2019-07-25_011903](https://user-images.githubusercontent.com/10646824/61814688-28c94400-ae7b-11e9-9075-e5cf6bbf91e5.jpg)
If it works well only in the training set, I don't think it's meaningful for the task of image restoration.

**Comment by primejava** [comment]
![00305](https://user-images.githubusercontent.com/10646824/61831337-20cfcb00-aea0-11e9-8f61-a4b4294bd775.png)
this is my test picture

**Comment by lyndonzheng** [comment]
@primejava First, all the results showed in our paper and project comes from the testing dataset, rather than the training sets. The [online demo](http://www.chuanxiaz.com/project/pluralistic/) also works on the testing dataset. You should get the similar result like our online demo. Second, the face painting model is trained on Celeba-HQ dataset, where the face is aligned. But for this GUI, there is no pre-processing for face-aligned.

**Comment by lyndonzheng** [comment]
That's the example showed in our video. I do some prepocessing to align my own face as same as the Celeba-HQ dataset. ![face](https://user-images.githubusercontent.com/8929977/61833643-8a9fa300-aea7-11e9-948b-496b7c3def06.png)

**Comment by primejava** [comment]
@lyndonzheng im sorry,but The online demo can't upload my picture,so can you tell me the details about how to align the faces in this picture?Actually, I can't understand what's wrong with this picture.thank you very much.

**Comment by primejava** [comment]
I still think this project is meaningless.

**Comment by zhenglilei** [comment]
> If you have to do some prepocessing about the picture, I still think the project is meaningless.

Face alignment is common and necessary in many face tasks. Without doing this, even face recognition performance will drop a lot. 

In contrast to face recognition, inpainting is still an open problem to solve. I don't think it's reasonable for you to make such conclusion on this good research work, just due to your single bad case.
