### ISSUE TITLE
about hinge loss

### ISSUE THREAD

**Issue by 2018hello** [lyndonzheng/Pluralistic-Inpainting#5]
hi!
I have a problem. 
If I use hinge loss, I see in Generator,  it will produce negative adv loss, while others are positive.
And the total loss is the sum of positive value and negative value .
Can you explain it?
Thanks a lot!

**Comment by lyndonzheng** [comment]
@2018hello For the hinge loss of GAN, we see it in the [self-attention GAN].(https://arxiv.org/pdf/1805.08318.pdf)
![image](https://user-images.githubusercontent.com/8929977/55270940-67d9f500-52e0-11e9-94d4-54104c519ad9.png) To minimize the negative adc loss in generator, the network actually tries make it large (close to the real). While in the discriminator, it tries to make real image gets large value and make the fake (generated) image gets small value. In this way, the discriminator can distinguish them.

**Comment by 2018hello** [comment]
Thanks  a lot! i got it!

**Comment by Alpe6825** [comment]
@lyndonzheng, @2018hello I don't unterstand L_G.

Is my assumption right, that y=1 means ,,real image" and G(z) tries to make D output 1 in L_G? That would result in a loss of -1 at this case. Is that right? Why is L_G not L_G=-min(0, -1 + D(G(z), y)). Than L_G would tries to reach a loss of 0, which makes more sense for me, since a negative loss value wouldn't be possible.
